spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa_shop
    username: iotsid
    password: iotsid1!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
